### ISSUE TITLE
Monotonic time conversion incorrect

### ISSUE THREAD

**Issue by lucbouchard1** [PolySat/libproc#10]
The code [here](https://github.com/PolySat/libproc/blob/master/proclib.c#L171) does the following to convert to microseconds:
```C
res = clock_gettime(CLOCK_MONOTONIC, &tp);
tv->tv_sec = tp.tv_sec;
tv->tv_usec = (tp.tv_nsec + 500 ) / 1000;
```
It should be multiplying by 1000 instead of dividing. Can someone review this to make sure I'm not crazy, @johnbellardo @Joshua-Anderson .

**Comment by johnbellardo** [comment]
1ns == 0.001us

**Comment by lucbouchard1** [comment]
Clearly I don't understand metric prefixes...
