### ISSUE TITLE
Add Async Process Command Response Functionality

### ISSUE THREAD

**Issue by Joshua-Anderson** [PolySat/libproc#7]
Right now we can call other processes, but the method for receiving the response, by adding the command  to the processes cmd configuration, is hacky.

The proposed solution is adding a async process function that allows you to call another process with a callback and timeout.

Serbinder implemented this in a branch of libproc for libhms,  but it's unsafe and needs some slight refactoring.

**Comment by lucbouchard1** [comment]
I want to +1 this. We should assign it to someone for the summer as it would extremely helpful.

**Comment by Joshua-Anderson** [comment]
This has been long resolved with libproc v3 and the xdr refactor
